services:
  # 1. Веб-панель администратора
  - type: web
    name: cafe-admin-panel
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_admin:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cafe-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: ADMIN_USERNAME
        sync: false # Устанавливается в панели Render
      - key: ADMIN_PASSWORD
        sync: false # Устанавливается в панели Render

  # 2. Телеграм-бот
  - type: worker
    name: telegram-cafe-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cafe-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Устанавливается в панели Render
      - key: ADMIN_TELEGRAM_ID
        sync: false # Устанавливается в панели Render

databases:
  - name: cafe-db
    databaseName: cafe_db
    user: cafe_user